### PR TITLE
feat: transparent bars and more discrete tab stacks

### PR DESCRIPTION
**Pull request by clementpoiret**
Hi!

Here I come with a very small update which:
- makes address bars with semi-transparent background so that it feels more integrated,
- I changed the stacked tabs stroke width and color so that it matches the new address bar better. I think it's more discrete this way. Previously it was using colorAccent as stroke, but with a gradient background it may seem odd. Using the more neural colorBg or colorBorder looked better to me.

Screenshot from 2023-07-31 11:14:23

What do you think about it?

### CODE REVIEW

**Comment by tovifun** [comment]
Hi, I feel that both of these commits are quite in line with my idea, making these two areas more harmonious with the background. I have already merged your commit🥰, and then I made some minor adjustments on top of yours, mainly optimizing the colors and adapting to some other situations in the status bar.

**Comment by clementpoiret** [comment]
I'm happy to ear that! :)
I also tried a minor change, maybe that using a fill instead of a border is more "modern"?

Example:
image

**Comment by tovifun** [comment]
I think from a UI perspective, it does indeed become more modern. However, I am a bit concerned that this might cause some functional misunderstandings because it doesn't quite look like a box(or Stack), and it bears some resemblance to the tab's selected state.

**Comment by tovifun** [comment]
We can continue to optimize it in the future. 🥰

**Comment by clementpoiret** [comment]
I completely understand!
With great pleasure :)

**Pull request merged**
