### PR TITLE
feat: updated dark theme

### PR DESCRIPTION
**Pull request by clementpoiret**
First, I'd like to say: wow! Very nice job :D
I just find the dark theme to be a bit strange compared to the light one, and as I like switching from light to dark based on the hour, I add a darker gradient and update the "too yellow" yellow, by a darker one matching the proposed gradient.

Screenshot:
Screenshot from 2023-07-28 15:25:47

I hope you'll like it :) 

Anyway, you leveled up my vivaldi, it's awesome!

### CODE REVIEW

**Comment by clementpoiret** [comment]
ps: the original dark theme is the ArcDarkPure.zip (matching the name in settings.json), mine is ArcDark.zip

**Comment by tovifun** [comment]
This theme looks great!👏 I've already merged it. Also, I just realized that if the address bar is open, I can optimize the color of the address bar so that it's not two black input boxes.😂

**Comment by tovifun** [comment]
BTW, may I ask what OS system are you using? It looks very harmonious as a whole.😍

**Comment by clementpoiret** [comment]
Thanks! Yeah that's a great idea for the address and search bars :)
And thanks for the comment on the OS, I use EndeavourOS, with Hyprland window manager, and waybar.
Hyprland is sometimes a bit buggy, mostly because of the combo Nvidia GPU + Wayland, but when everything is setup that's awesome!

**Comment by tovifun** [comment]
It's really cool!

**Comment by themysteryboy** [comment]
> First, I'd like to say: wow! Very nice job :D I just find the dark theme to be a bit strange compared to the light one, and as I like switching from light to dark based on the hour, I add a darker gradient and update the "too yellow" yellow, by a darker one matching the proposed gradient.
> 
> Screenshot: Screenshot from 2023-07-28 15:25:47
> 
> I hope you'll like it :)
> 
> Anyway, you leveled up my vivaldi, it's awesome!

can u share how do u make the close and other buttons disappear in linux with hyprland wm?

**Comment by clementpoiret** [comment]
> can u share how do u make the close and other buttons disappear in linux with hyprland wm?

Here is my hyprland config :) https://github.com/clementpoiret/dotfiles/blob/main/dot_config/hypr/hyprland.conf
(Warning: since last update, blur config is broken, I need to fix that)

**Comment by clementpoiret** [comment]
[themysteryboy](https://github.com/themysteryboy) Hmm I just made a fresh install of hyprland on another computer, and I got the buttons you want to hide. Strange. I fixed it by force vivaldi to be in tile mode:

`windowrulev2 = tile, class:^(Vivaldi-stable)$`

Depending on your install, the class name can change, you can check it when you have an open vivaldi window using `hyprctl clients`

**Pull request merged**
